spring:
  jpa:
    database: "postgresql"
    show-sql: "true"
    properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQL10Dialect"

  database.driverClassName: "org.postgresql.Driver"

  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://localhost:5432/eagle-eye"
    username: "postgres"
    password: "{cipher}4e2b0258026aee15b724fbb9df9f731bb53e71b96a616449b9904bb3de5a62a6"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

  zipkin.baseUrl: "http://localhost:9411"
    
  cloud.config:
    allowOverride: true
    overrideNone: true
    overrideSystemProperties: false

signing.key: "a48snaw1o05p7xj4"
